# Generated by Django 5.0.3 on 2024-04-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_currency_customuser_change_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='change_currency',
            field=models.CharField(choices=[('£', 'British Pound'), ('$', 'US Dollar'), ('€', 'Euro')], default='£', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='change_currency',
            field=models.CharField(choices=[('$', 'US Dollar'), ('£', 'British Pound'), ('€', 'Euro')], default='£', max_length=3),
        ),
    ]
